Do not return result if decode in invalid
tzvetkoff/hashids.c pull request #28
Opened 2019-03-17 13:13 UTC by olekenneth

If the salt is invalid set the numbers to 0 and `hashids_errno = HASHIDS_ERROR_INVALID_HASH`.

This is done by encode the result of the decode and match the against the origin hash.
Just like the JS lib does: https://github.com/ivanakimov/hashids.js/blob/73bd48dab54476bc6fb46d1da67d0697c2e366ce/lib/hashids.js#L262

2019-03-18 14:20 UTC, tzvetkoff commented
Why would anyone want to clear out the resulting array in case of an error?

The _undefined_ behavior was pretty much what I intended in the first place.

Furthermore, if you exceed the amount of numbers in the result, you want to simply return out - for example, you might want to decode just 1 number from a hash that contains 2 or more.

And last but not least, strict checking is something that _is_ considered optional in `hashids_decode`.
As stated in the [README](https://github.com/tzvetkoff/hashids.c#usage), *nothing* should be done automagically.

If you want to do strict decode checking, your best bet is to do it in your app code.
Should we start doing this, it will drastically decrease performance - and performance is something @thedrow helped a lot to optimize for in the past.

I am, however, not closing the PR since I still need to think about adding a `hashids_decode_safe` (or something like that) that will do the strict decode checks - this way we'll not alter the current behavior (which I did one too many times since `v1.0.0` ☹️)

2019-03-18 18:31 UTC, olekenneth commented
Yes! I see your point. But still, now the output is indistinguishable between hashes decoded with correct salt and without.

But like you say, maybe this should be it's own function or parameter.

2019-03-31 10:54 UTC, olekenneth commented
More I can do to push this forward?

The reason for me to commit this is because I tried to use the module and got unexpected result, I therefor assume others will too. Also since the logic varies from the javascript and probably other implementations I think this code is needed.

2019-03-31 14:07 UTC, thedrow requested changes

2019-03-31 14:07 UTC, thedrow commented on src/hashids.c
> +        *(numbers + i) = 0;
I strongly prefer to use the array syntax here.
It's much clearer.

2019-03-31 14:07 UTC, thedrow commented on src/hashids.c
> +        _hashids_clear_numbers(numbers_start, numbers_count);
Shouldn't we set an error here?

2019-03-31 14:07 UTC, thedrow commented on src/hashids.c
> +        hashids_free_f(str_cpy);
Shouldn't we set an error here?

2022-10-25 18:56 UTC, closed without merging